services:
  bot:
    image: "anonflow"
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      org.opencontainers.image.version: "${VERSION:?VERSION is not set. Use 'python manage.py deploy'}"
    volumes:
      - ./rules/:/app/rules/
      - ./config.yml:/app/config.yml
